{{- if .Values.assign.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: assign-data

  annotations:
    assign.ukserp.ac.uk/component: "ydb"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.assign.persistence.persistentVolume.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  labels:
    component: ydb
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ include "assign.labels.chart" . }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.assign.persistence.persistentVolume.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  volumeMode: Filesystem

  persistentVolumeReclaimPolicy: {{ .Values.assign.persistence.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.assign.persistence.storageClassName }}

  capacity:
    storage: {{ .Values.assign.persistence.capacity }}

  accessModes:
    - ReadWriteOnce
{{- end }}