{{- if .Values.assign.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "assign.auth.secret" . }}

  annotations:
    assign.ukserp.ac.uk/component: "ydb"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.assign.auth.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  labels:
    component: ydb
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ include "assign.labels.chart" . }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.assign.auth.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

type: Opaque
stringData:
  username: "{{ .Values.assign.auth.username }}"
  password: "{{ .Values.assign.auth.password }}"
  ADDWEBAUTH.m: |
    ADDWEBAUTH ; ; 15/11/24
     s keyvalue="FAKE_KEY" ; bring these in from vault?
     s username="{{ .Values.assign.auth.username }}"
     s userpass="{{ .Values.assign.auth.password }}"

     s ^ICONFIG("KEY")=keyvalue
     s Y=$$TORCFOUR^EWEBRC4(userpass,^ICONFIG("KEY"))
     s ^BUSER("USER",username)=Y
     q
{{- end }}
