{{- if .Values.assign.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "assign.persistence.volumeName" . }}

  annotations:
    assign.ukserp.ac.uk/component: "ydb"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.assign.persistence.persistentVolumeClaim.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  labels:
    component: ydb
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ include "assign.labels.chart" . }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.assign.persistence.persistentVolumeClaim.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  volumeMode: Filesystem

  volumeName: {{ include "assign.persistence.volumeName" . }}
  storageClassName: {{ .Values.assign.persistence.storageClassName }}

  resources:
    requests:
      storage: {{ .Values.assign.persistence.capacity }}

  accessModes:
    - ReadWriteOnce
{{- end }}