services:
  db:
    image: assign-container:pr-8
    ports:
      - "9080:9080"
      - "9081:9081"
    volumes:
      - type: volume
        source: db-data
        target: /data/ABP
volumes:
  db-data: