services:
  db:
    image: assign-container:pr-8
    environment:
      assign_sha: "ebbee2f"
    ports:
      - "9080:9080"
      - "9081:9081"
    volumes:
      - type: volume
        source: db-data
        target: /data
volumes:
  db-data: