services:
  db:
    image: assign:1.0.0
    environment:
      assign_sha: ""
      start_assign: "false"
      trigger_abp_load: "false"
    ports:
      - "9080:9080"
      - "9081:9081"
    volumes:
      - type: volume
        source: db-data
        target: /data
volumes:
  db-data: