name: ASSIGN YDB Container

on:
  pull_request:
    # Ignore PRs on branches specifically intended for other assets
    branches-ignore: []
    # Only consider PRs that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/assign-container.yaml'
      - 'containers/assign/**'
      - 'startup_scripts/**'
  push:
    # Only release off of release and maintenance branches for this asset
    branches:
      - 'main'
    # Only consider pushes that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/assign-container.yaml'
      - 'containers/assign/**'
      - 'startup_scripts/**'

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Needed to generate releases safely
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Job name must be unique across repo to target
  # branch protection rules "required checks" properly!
  assign-container:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-container.yaml@v2.0.3-containers
    with:
      job-name: assign-container
      comment-pr: 'true'
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/assign
      release-tag-format: 'v${version}-assign-container'
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: containers/assign/Dockerfile
      build-context: .
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
